apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-deployment
spec:
  replicas: 2                           # Must be 'replicas', not 'replica'
  selector:
    matchLabels:                        # Must be 'matchLabels', not 'matchLables'
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
        - name: flask-todo
          image: gowdaamith/devops-todo-app:latest
          ports:
            - containerPort: 5000       # Must be 'containerPort', not 'containernPort'

